name: Deploy image to GHCR
permissions: write-all

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/Push image
        run: |
            docker build . --tag ghcr.io/minhvo-dev/dotnet-opencv-image:latest
            docker push ghcr.io/minhvo-dev/dotnet-opencv-image:latest